FROM node:20-bookworm-slim

WORKDIR /workspace

COPY package.json package-lock.json ./
COPY server/package.json ./server/package.json
COPY client/package.json ./client/package.json

RUN npm ci

COPY . .

CMD ["npm", "run", "dev:server"]
